using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Refitter.Core;

/// <summary>
/// Configuration for what code generation features are enabled.
/// </summary>
[ExcludeFromCodeCoverage]
public class CodeGenerationConfig
{
    /// <summary>
    /// Gets or sets a value indicating whether contracts should be generated.
    /// </summary>
    [Description("Generate contracts. Default is true.")]
    public bool GenerateContracts { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether clients should be generated.
    /// </summary>
    [Description("Generate clients. Default is true.")]
    public bool GenerateClients { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether clients should implement IDisposable.
    /// </summary>
    [Description("Generate clients that implement IDisposable.")]
    public bool GenerateDisposableClients { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether XML doc comments should be generated.
    /// </summary>
    [Description("Generate XML doc comments. Default is true.")]
    public bool GenerateXmlDocCodeComments { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether <c>ApiException</c> and <c>IApiResponse</c> should be documented with
    /// the relevant status codes specified in the OpenAPI document.
    /// </summary>
    [Description(
        """
        Indicating whether <c>ApiException</c> and <c>IApiResponse</c> should be documented with
        the relevant status codes specified in the OpenAPI document.
        """
    )]
    public bool GenerateStatusCodeComments { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to add auto-generated header.
    /// </summary>
    [Description("Add auto-generated header. Default is true.")]
    public bool AddAutoGeneratedHeader { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to add accept headers [Headers("Accept: application/json")].
    /// </summary>
    [Description("Add accept headers [Headers(\"Accept: application/json\")]. Default is true.")]
    public bool AddAcceptHeaders { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to add content-type headers [Headers("Content-Type: application/json")].
    /// </summary>
    [Description("Add content-type headers [Headers(\"Content-Type: application/json\")]. Default is true.")]
    public bool AddContentTypeHeaders { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to return <c>IApiResponse</c> objects.
    /// </summary>
    [Description("Return IApiResponse objects.")]
    public bool ReturnIApiResponse { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether to return IObservable or Task
    /// </summary>
    [Description("Return IObservable or Task.")]
    public bool ReturnIObservable { get; set; }

    /// <summary>
    /// Gets or sets a dictionary of operation ids and a specific response type that they should use. The type is
    /// wrapped in a task, but otherwise unmodified (so make sure that the namespaces are imported or specified).
    /// </summary>
    [Description(
        """
        A dictionary of operation ids and a specific response type that they should use.
        The type is wrapped in a task, but otherwise unmodified (so make sure that the namespaces are imported or specified).
        """
    )]
    public Dictionary<string, string> ResponseTypeOverride { get; set; } = new();

    /// <summary>
    /// Gets or sets a value indicating whether to generate operation headers.
    /// </summary>
    [Description("Generate operation headers. Default is true.")]
    public bool GenerateOperationHeaders { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to generate deprecated operations, otherwise <c>false</c>
    /// </summary>
    [Description("Generate deprecated operations. Default is true.")]
    public bool GenerateDeprecatedOperations { get; set; } = true;

    /// <summary>
    /// Set to <c>true</c> to Generate a Refit interface for each endpoint
    /// </summary>
    [Description("Generate a Refit interface for each endpoint.")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public MultipleInterfaces MultipleInterfaces { get; set; }

    /// <summary>
    /// Generate operation names using pattern.
    /// When using <see cref="MultipleInterfaces"/> <see cref="Refitter.Core.MultipleInterfaces.ByEndpoint"/>, this is name of the Execute() method in the interface.
    /// </summary>
    [Description(
        """
        Generate operation names using pattern. When using --multiple-interfaces ByEndpoint,
        this is name of the Execute() method in the interface.
        """
    )]
    public string? OperationNameTemplate { get; set; }

    /// <summary>
    /// The NSwag IOperationNameGenerator implementation to use
    /// </summary>
    [Description("The NSwag IOperationNameGenerator implementation to use.")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public OperationNameGeneratorTypes OperationNameGenerator { get; set; }

    /// <summary>
    /// Set to <c>false</c> to skip default additional properties. Default is <c>true</c>
    /// </summary>
    [Description("Skip default additional properties. Default is true.")]
    public bool GenerateDefaultAdditionalProperties { get; set; } = true;

    /// <summary>
    /// Gets or sets a directory path which contains liquid templates for NSwag. If null or empty, uses default
    /// templates.
    /// </summary>
    [Description("Custom directory with NSwag fluid templates for code generation. Default is null which uses the default NSwag templates. See https://github.com/RicoSuter/NSwag/wiki/Templates")]
    public string? CustomTemplateDirectory { get; set; }
}
