using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Refitter.Core;

[ExcludeFromCodeCoverage]
public class CodeGenerationConfig
{
    [Description("Generate contracts. Default is true.")]
    public bool GenerateContracts { get; set; } = true;

    [Description("Generate clients. Default is true.")]
    public bool GenerateClients { get; set; } = true;

    [Description("Generate clients that implement IDisposable.")]
    public bool GenerateDisposableClients { get; set; }

    [Description("Generate XML doc comments. Default is true.")]
    public bool GenerateXmlDocCodeComments { get; set; } = true;

    [Description(
        """
        Indicating whether <c>ApiException</c> and <c>IApiResponse</c> should be documented with
        the relevant status codes specified in the OpenAPI document.
        """
    )]
    public bool GenerateStatusCodeComments { get; set; } = true;

    [Description("Add auto-generated header. Default is true.")]
    public bool AddAutoGeneratedHeader { get; set; } = true;

    [Description("Add accept headers [Headers(\"Accept: application/json\")]. Default is true.")]
    public bool AddAcceptHeaders { get; set; } = true;

    [Description("Add content-type headers [Headers(\"Content-Type: application/json\")]. Default is true.")]
    public bool AddContentTypeHeaders { get; set; } = true;

    [Description("Return IApiResponse objects.")]
    public bool ReturnIApiResponse { get; set; }

    [Description("Return IObservable or Task.")]
    public bool ReturnIObservable { get; set; }

    [Description(
        """
        AddAcceptHeaders dictionary of operation ids and a specific response type that they should use.
        The type is wrapped in a task, but otherwise unmodified (so make sure that the namespaces are imported or specified).
        """
    )]
    public Dictionary<string, string> ResponseTypeOverride { get; set; } = new();

    [Description("Generate operation headers. Default is true.")]
    public bool GenerateOperationHeaders { get; set; } = true;

    [Description("Generate deprecated operations. Default is true.")]
    public bool GenerateDeprecatedOperations { get; set; } = true;

    [Description("Generate a Refit interface for each endpoint.")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public MultipleInterfaces MultipleInterfaces { get; set; }

    [Description(
        """
        Generate operation names using pattern. When using --multiple-interfaces ByEndpoint,
        this is name of the Execute() method in the interface.
        """
    )]
    public string? OperationNameTemplate { get; set; }

    [Description("The NSwag IOperationNameGenerator implementation to use.")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public OperationNameGeneratorTypes OperationNameGenerator { get; set; }

    [Description("Skip default additional properties. Default is true.")]
    public bool GenerateDefaultAdditionalProperties { get; set; } = true;

    [Description("Custom directory with NSwag fluid templates for code generation. Default is null which uses the default NSwag templates. See https://github.com/RicoSuter/NSwag/wiki/Templates")]
    public string? CustomTemplateDirectory { get; set; }
}
