namespace Refitter.Core;

/// <summary>
/// Configuration for where generated output files are placed.
/// </summary>
public interface IOutputConfiguration
{
    /// <summary>
    /// Gets or sets the relative path to a folder in which the output files are generated. (default: ./Generated)
    /// </summary>
    string OutputFolder { get; }

    /// <summary>
    /// Gets or sets the relative path to a folder where to store the generated contracts. (default: ./Generated)
    /// </summary>
    string? ContractsOutputFolder { get; }

    /// <summary>
    /// Gets or sets the filename of the generated code.
    /// </summary>
    string? OutputFilename { get; }

    /// <summary>
    /// Gets or sets a value indicating whether to generate multiple files.
    /// </summary>
    bool GenerateMultipleFiles { get; }

    /// <summary>
    /// Gets or sets a value indicating whether to add auto-generated header.
    /// </summary>
    bool AddAutoGeneratedHeader { get; }
}
