using Refitter.Core.Settings;

namespace Refitter.Core;

public static class SettingsBundleExtensions
{
    public static RefitGeneratorSettings ToLegacySettings(this SettingsBundle bundle)
    {
        var result = new RefitGeneratorSettings();

        if (bundle.TryGet<GenerationConfig>(out var generation) && generation is not null)
        {
            result.GenerateContracts = generation.GenerateContracts;
            result.GenerateClients = generation.GenerateClients;
            result.GenerateDisposableClients = generation.GenerateDisposableClients;
            result.GenerateDeprecatedOperations = generation.GenerateDeprecatedOperations;
            result.GenerateDefaultAdditionalProperties = generation.GenerateDefaultAdditionalProperties;
            result.MultipleInterfaces = generation.MultipleInterfaces;
            result.OperationNameTemplate = generation.OperationNameTemplate;
            result.OperationNameGenerator = generation.OperationNameGenerator;
            result.GenerateOperationHeaders = generation.GenerateOperationHeaders;
            result.GenerateXmlDocCodeComments = generation.GenerateXmlDocCodeComments;
            result.GenerateStatusCodeComments = generation.GenerateStatusCodeComments;
            result.AddAutoGeneratedHeader = generation.AddAutoGeneratedHeader;
            result.AddAcceptHeaders = generation.AddAcceptHeaders;
            result.AddContentTypeHeaders = generation.AddContentTypeHeaders;
            result.ReturnIApiResponse = generation.ReturnIApiResponse;
            result.ReturnIObservable = generation.ReturnIObservable;
            result.ResponseTypeOverride = generation.ResponseTypeOverride ?? [];
            result.CustomTemplateDirectory = generation.CustomTemplateDirectory;
        }

        if (bundle.TryGet<OutputConfigSlice>(out var output) && output is not null)
        {
            result.Namespace = output.Namespace;
            result.ContractsNamespace = output.ContractsNamespace;
            result.OutputFolder = output.OutputFolder;
            result.ContractsOutputFolder = output.ContractsOutputFolder;
            result.OutputFilename = output.OutputFilename;
            result.GenerateMultipleFiles = output.GenerateMultipleFiles;
        }

        if (bundle.TryGet<OpenApiSourceConfigSlice>(out var source) && source is not null)
        {
            result.OpenApiPath = source.OpenApiPath;
            result.OpenApiPaths = source.OpenApiPaths;
        }

        if (bundle.TryGet<FilterConfigSlice>(out var filter) && filter is not null)
        {
            result.IncludeTags = filter.IncludeTags ?? [];
            result.IncludePathMatches = filter.IncludePathMatches ?? [];
            result.IgnoredOperationHeaders = filter.IgnoredOperationHeaders ?? [];
            result.AdditionalNamespaces = filter.AdditionalNamespaces ?? [];
            result.ExcludeNamespaces = filter.ExcludeNamespaces ?? [];
        }

        if (bundle.TryGet<SchemaConfigSlice>(out var schema) && schema is not null)
        {
            result.TrimUnusedSchema = schema.TrimUnusedSchema;
            result.KeepSchemaPatterns = schema.KeepSchemaPatterns ?? [];
            result.IncludeInheritanceHierarchy = schema.IncludeInheritanceHierarchy;
        }

        if (bundle.TryGet<TypeConfigSlice>(out var typeConfig) && typeConfig is not null)
        {
            result.TypeAccessibility = typeConfig.TypeAccessibility;
            result.PropertyNamingPolicy = typeConfig.PropertyNamingPolicy;
            result.ImmutableRecords = typeConfig.ImmutableRecords;
            result.ContractTypeSuffix = typeConfig.ContractTypeSuffix;
        }

        if (bundle.TryGet<ParameterConfigSlice>(out var parameter) && parameter is not null)
        {
            result.UseCancellationTokens = parameter.UseCancellationTokens;
            result.UseIsoDateFormat = parameter.UseIsoDateFormat;
            result.OptionalParameters = parameter.OptionalParameters;
            result.UseDynamicQuerystringParameters = parameter.UseDynamicQuerystringParameters;
            result.CollectionFormat = parameter.CollectionFormat;
        }

        if (bundle.TryGet<FeatureConfigSlice>(out var feature) && feature is not null)
        {
            result.UsePolymorphicSerialization = feature.UsePolymorphicSerialization;
            result.AuthenticationHeaderStyle = feature.AuthenticationHeaderStyle;
            result.SecurityScheme = feature.SecurityScheme;
            result.GenerateJsonSerializerContext = feature.GenerateJsonSerializerContext;
        }

        return result;
    }
}
