using System.ComponentModel;
using Refitter.Core;
using Spectre.Console;
using Spectre.Console.Cli;
using ValidationResult = Spectre.Console.ValidationResult;


var app = new CommandApp<GenerateCommand>();
app.Configure(
    config => config
        .SetApplicationName("refitter")
        .SetApplicationVersion(typeof(GenerateCommand).Assembly.GetName().Version!.ToString())
        .AddExample(
            new[]
            {
                "./openapi.json",
                "--namespace",
                "\"Your.Namespace.Of.Choice.GeneratedCode\"",
                "--output",
                "./Output.cs"
            }));
return app.Run(args);

internal sealed class GenerateCommand : AsyncCommand<GenerateCommand.Settings>
{
    public sealed class Settings : CommandSettings
    {
        [Description("Path to OpenAPI Specification file")]
        [CommandArgument(0, "[input file]")]
        public string? OpenApiPath { get; set; }

        [Description("Default namespace to use for generated types")]
        [CommandOption("-n|--namespace")]
        [DefaultValue("GeneratedCode")]
        public string? Namespace { get; set; }

        [Description("Path to Output file")]
        [CommandOption("-o|--output")]
        [DefaultValue("Output.cs")]
        public string? OutputPath { get; set; }

        [Description("Don't add <auto-generated> header to output file")]
        [CommandOption("--no-auto-generated-header")]
        [DefaultValue(false)]
        public bool NoAutoGeneratedHeader { get; set; }

        [Description("Don't generate contract types")]
        [CommandOption("--interface-only")]
        [DefaultValue(false)]
        public bool InterfaceOnly { get; set; }

        [Description("Return Task<IApiResponse<T>> instead of Task<T>")]
        [CommandOption("--use-api-response")]
        [DefaultValue(false)]
        public bool ReturnIApiResponse { get; set; }
    }

    public override ValidationResult Validate(CommandContext context, Settings settings)
    {
        if (string.IsNullOrWhiteSpace(settings.OpenApiPath))
            return ValidationResult.Error("Input file is required");

        if (IsUrl(settings.OpenApiPath))
            return base.Validate(context, settings);
        
        return File.Exists(settings.OpenApiPath)
            ? base.Validate(context, settings)
            : ValidationResult.Error($"File not found - {Path.GetFullPath(settings.OpenApiPath)}");
    }

    public override async Task<int> ExecuteAsync(CommandContext context, Settings settings)
    {
        var refitGeneratorSettings = new RefitGeneratorSettings
        {
            OpenApiPath = settings.OpenApiPath!,
            Namespace = settings.Namespace ?? "GeneratedCode",
            AddAutoGeneratedHeader = !settings.NoAutoGeneratedHeader,
            GenerateContracts = !settings.InterfaceOnly,
            ReturnIApiResponse = settings.ReturnIApiResponse
        };

        try
        {
            var generator = await RefitGenerator.CreateAsync(refitGeneratorSettings);
            var code = generator.Generate();
            await File.WriteAllTextAsync(settings.OutputPath ?? "Output.cs", code);
            AnsiConsole.MarkupLine($"[green]Output: {code.Length} bytes[/]");
            return 0;
        }
        catch (Exception e)
        {
            AnsiConsole.MarkupLine($"[red]Error:{Environment.NewLine}{e.Message}[/]");
            AnsiConsole.MarkupLine($"[yellow]Stack Trace:{Environment.NewLine}{e.StackTrace}[/]");
            return e.HResult;
        }
    }

    private bool IsUrl(string openApiPath)
    {
        return Uri.TryCreate(openApiPath, UriKind.Absolute, out var uriResult)
               && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);
    }

}