using Refitter.Core;

namespace Refitter;

internal static class SettingsMapper
{
    public static RefitGeneratorSettings Map(Settings settings)
    {
        settings.TryGetAuthenticationHeaderStyle(out var authenticationHeaderStyle, out _);

        var result = new RefitGeneratorSettings();

        ConventionMapper.Map(settings, result);

        result.OpenApiPath = settings.OpenApiPath!;
        result.Namespace = settings.Namespace ?? "GeneratedCode";
        result.AddAutoGeneratedHeader = !settings.NoAutoGeneratedHeader;
        result.AddAcceptHeaders = !settings.NoAcceptHeaders;
        result.GenerateContracts = !settings.InterfaceOnly;
        result.GenerateClients = !settings.ContractOnly;
        result.GenerateOperationHeaders = !settings.NoOperationHeaders;
        result.GenerateXmlDocCodeComments = !settings.NoXmlDocCodeComments;
        result.GenerateDeprecatedOperations = !settings.NoDeprecatedOperations;
        result.GenerateDefaultAdditionalProperties = !settings.SkipDefaultAdditionalProperties;
        result.AllowRemoteReferences = settings.AllowRemoteReferences;
        result.TypeAccessibility = settings.InternalTypeAccessibility
            ? Core.TypeAccessibility.Internal
            : Core.TypeAccessibility.Public;
        result.IncludePathMatches = settings.MatchPaths ?? [];
        result.IncludeTags = settings.Tags ?? [];
        result.OptionalParameters = settings.OptionalNullableParameters;
        result.ContractsOutputFolder = settings.ContractsOutputPath ?? settings.OutputPath;
        result.GenerateMultipleFiles = settings.GenerateMultipleFiles
            || !string.IsNullOrWhiteSpace(settings.ContractsOutputPath);
        result.ApizrSettings = settings.UseApizr ? new ApizrSettings() : null;
        result.CodeGeneratorSettings = new CodeGeneratorSettings
        {
            InlineJsonConverters = !settings.NoInlineJsonConverters,
            IntegerType = settings.IntegerType,
            JsonLibraryVersion = settings.JsonLibraryVersion ?? 8.0m,
        };
        result.AuthenticationHeaderStyle = authenticationHeaderStyle;
        result.AdditionalNamespaces = settings.AdditionalNamespaces!;

        return result;
    }
}
