using Refitter.Core;
using Refitter.Core.Settings;

namespace Refitter;

internal static class SettingsToBundleMapper
{
    public static SettingsBundle Map(Settings settings)
    {
        settings.TryGetAuthenticationHeaderStyle(out var authStyle, out _);

        var builder = new SettingsBuilder();

        builder.With(new GenerationConfig
        {
            GenerateContracts = !settings.InterfaceOnly,
            GenerateClients = !settings.ContractOnly,
            GenerateDisposableClients = settings.GenerateDisposableClients,
            GenerateDeprecatedOperations = !settings.NoDeprecatedOperations,
            GenerateDefaultAdditionalProperties = !settings.SkipDefaultAdditionalProperties,
            MultipleInterfaces = settings.MultipleInterfaces,
            OperationNameTemplate = settings.OperationNameTemplate,
            OperationNameGenerator = settings.OperationNameGenerator,
            GenerateOperationHeaders = !settings.NoOperationHeaders,
            GenerateXmlDocCodeComments = !settings.NoXmlDocCodeComments,
            GenerateStatusCodeComments = true,
            AddAutoGeneratedHeader = !settings.NoAutoGeneratedHeader,
            AddAcceptHeaders = !settings.NoAcceptHeaders,
            AddContentTypeHeaders = true,
            ReturnIApiResponse = settings.ReturnIApiResponse,
            ReturnIObservable = settings.ReturnIObservable,
            ResponseTypeOverride = null,
            CustomTemplateDirectory = settings.CustomTemplateDirectory,
        });

        builder.With(new OutputConfigSlice
        {
            Namespace = settings.Namespace ?? "GeneratedCode",
            ContractsNamespace = settings.ContractsNamespace,
            OutputFolder = "./Generated",
            ContractsOutputFolder = settings.ContractsOutputPath ?? settings.OutputPath,
            OutputFilename = null,
            GenerateMultipleFiles = settings.GenerateMultipleFiles
                || !string.IsNullOrWhiteSpace(settings.ContractsOutputPath),
        });

        builder.With(new OpenApiSourceConfigSlice
        {
            OpenApiPath = settings.OpenApiPath,
            OpenApiPaths = null,
        });

        builder.With(new FilterConfigSlice
        {
            IncludeTags = settings.Tags ?? [],
            IncludePathMatches = settings.MatchPaths ?? [],
            IgnoredOperationHeaders = settings.IgnoredOperationHeaders ?? [],
            AdditionalNamespaces = settings.AdditionalNamespaces ?? [],
            ExcludeNamespaces = settings.ExcludeNamespaces ?? [],
        });

        builder.With(new SchemaConfigSlice
        {
            TrimUnusedSchema = settings.TrimUnusedSchema,
            KeepSchemaPatterns = settings.KeepSchemaPatterns ?? [],
            IncludeInheritanceHierarchy = settings.IncludeInheritanceHierarchy,
        });

        builder.With(new TypeConfigSlice
        {
            TypeAccessibility = settings.InternalTypeAccessibility
                ? Core.TypeAccessibility.Internal
                : Core.TypeAccessibility.Public,
            PropertyNamingPolicy = settings.PropertyNamingPolicy,
            ImmutableRecords = settings.ImmutableRecords,
            ContractTypeSuffix = null,
        });

        builder.With(new ParameterConfigSlice
        {
            UseCancellationTokens = settings.UseCancellationTokens,
            UseIsoDateFormat = settings.UseIsoDateFormat,
            OptionalParameters = settings.OptionalNullableParameters,
            UseDynamicQuerystringParameters = settings.UseDynamicQuerystringParameters,
            CollectionFormat = settings.CollectionFormat,
        });

        builder.With(new FeatureConfigSlice
        {
            UsePolymorphicSerialization = settings.UsePolymorphicSerialization,
            AuthenticationHeaderStyle = authStyle,
            SecurityScheme = settings.SecurityScheme,
            GenerateJsonSerializerContext = settings.GenerateJsonSerializerContext,
        });

        var result = builder.Build();
        result.ThrowIfInvalid();

        return result.Bundle!;
    }
}
