openapi: 3.0.1
info:
  title: Unrecognized enum values
  version: 1.0.0
paths:
  /pets:
    get:
      parameters:
        - name: a
          in: body
          schema:
            type: string
        - name: b
          in: query
          style: sideways
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    weird:
      type: carrier-pigeon
    key:
      type: apiKey
      name: X-Key
      in: cookiejar
    http:
      type: http
      scheme: bearer
