openapi: 3.1.0
$schema: https://example.com/schema
bogusRoot: true
info:
  title: Unknown properties
  version: 1.0.0
  summary: allowed in 3.1
  bogusInfo: 1
paths:
  /pets:
    get:
      bogusOperation: true
      responses:
        '200':
          description: OK
components:
  schemas:
    Pet:
      type: object
      $comment: allowed
      properties:
        name:
          type: [string, 'null']
          unknownKeyword: 1
