using System.Text;
using NSwag;

namespace Refitter.Core;

internal sealed class GeneratorPipeline
{
    private readonly InterfaceGenerator interfaceGenerator;
    private readonly IReadOnlyList<IContractsPostProcessor> contractsPostProcessors;

    internal GeneratorPipeline(
        InterfaceGenerator interfaceGenerator,
        IEnumerable<IContractsPostProcessor> contractsPostProcessors)
    {
        this.interfaceGenerator = interfaceGenerator;
        this.contractsPostProcessors = contractsPostProcessors.ToArray();
    }

    public GenerationResult Run(
        OpenApiDocument document,
        RefitGeneratorSettings settings,
        CustomCSharpClientGenerator generator)
    {
        var contracts = generator.GenerateFile();
        foreach (var postProcessor in contractsPostProcessors)
            contracts = postProcessor.Process(document, settings, contracts);

        var serializerContext = GenerateJsonSerializerContext(document, settings, contracts);
        var interfaces = GenerateClient(document, settings, interfaceGenerator);
        var interfaceNames = interfaces.Select(c => c.TypeName).ToArray();
        var title = settings.Naming.UseOpenApiTitle && !string.IsNullOrWhiteSpace(document.Info?.Title)
            ? document.Info!.Title.Sanitize()
            : settings.Naming.InterfaceName;
        var dependencyInjectionCode = settings.ApizrSettings != null
            ? ApizrRegistrationGenerator.Generate(settings, interfaceNames, title)
            : DependencyInjectionGenerator.Generate(settings, interfaceNames);

        return new(contracts, interfaces, serializerContext, dependencyInjectionCode, interfaceNames);
    }

    private static IInterfacePartitioning GetInterfacePartitioning(
        OpenApiDocument document,
        RefitGeneratorSettings settings)
    {
        return settings.MultipleInterfaces switch
        {
            MultipleInterfaces.ByEndpoint => new ByEndpointInterfacePartitioning(settings),
            MultipleInterfaces.ByTag => new ByTagInterfacePartitioning(settings, document),
            _ => new SingleInterfacePartitioning(settings),
        };
    }

    private static string GenerateJsonSerializerContext(
        OpenApiDocument document,
        RefitGeneratorSettings settings,
        string contracts) =>
        settings is { GenerateJsonSerializerContext: true, GenerateContracts: true }
            ? JsonSerializerContextGenerator.Generate(contracts, settings, document.Info?.Title)
            : string.Empty;

    private static IReadOnlyCollection<GeneratedCode> GenerateClient(
        OpenApiDocument document,
        RefitGeneratorSettings settings,
        InterfaceGenerator interfaceGenerator)
    {
        var code = new StringBuilder();
        GenerateAutoGeneratedHeader(settings, code);

        code.AppendLine()
            .AppendLine(RefitInterfaceImports.GenerateNamespaceImports(settings))
            .AppendLine();

        if (settings.AdditionalNamespaces.Length != 0)
        {
            foreach (var ns in settings.AdditionalNamespaces)
            {
                code.AppendLine($"using {ns};");
            }

            code.AppendLine();
        }

        code.AppendLine("#nullable enable annotations");
        code.AppendLine();

        var partitioning = GetInterfacePartitioning(document, settings);
        var refitInterfaces = interfaceGenerator.Generate(partitioning);
        var generatedCodes = refitInterfaces as GeneratedCode[] ?? refitInterfaces.ToArray();

        if (settings.GenerateMultipleFiles)
        {
            for (int i = 0; i < generatedCodes.Length; i++)
            {
                generatedCodes[i] = generatedCodes[i] with
                {
                    Content = code +
                              $$"""
                                namespace {{settings.Namespace}}
                                {
                                {{generatedCodes[i].Content}}
                                }
                                """,
                };
            }

            return generatedCodes;
        }

        code.AppendLine($"namespace {settings.Namespace}");
        code.AppendLine("{");

        foreach (var generatedCode in generatedCodes)
        {
            code.AppendLine(generatedCode.Content);
        }

        code.Append("}");

        return new[]
            {
                new GeneratedCode(generatedCodes.First().TypeName, code.ToString())
            }
            .Union(
                generatedCodes
                    .Skip(1)
                    .Select(c => new GeneratedCode(c.TypeName, string.Empty)))
            .ToArray();
    }

    private static void GenerateAutoGeneratedHeader(RefitGeneratorSettings settings, StringBuilder code)
    {
        if (!settings.AddAutoGeneratedHeader)
            return;

        code.AppendLine(
            $$"""
            // <auto-generated>
            //     This code was generated by Refitter version {{VersionHelper.GetVersion()}}.
            // </auto-generated>

            """);
    }
}

internal record GenerationResult(
    string Contracts,
    IReadOnlyCollection<GeneratedCode> Interfaces,
    string SerializerContext,
    string DependencyInjectionCode,
    string[] InterfaceNames);
