using FluentAssertions;
using Refitter.Core;
using Refitter.Tests.Build;
using Refitter.Tests.TestUtilities;
using TUnit.Core;

namespace Refitter.Tests.Scenarios;

public class AllHeadersDisabledTests
{
    private const string OpenApiSpec = @"
{
  ""openapi"": ""3.0.0"",
  ""info"": {
    ""title"": ""Test API"",
    ""version"": ""1.0.0""
  },
  ""paths"": {
    ""/api/items"": {
      ""get"": {
        ""operationId"": ""getItems"",
        ""summary"": ""Get items"",
        ""responses"": {
          ""200"": {
            ""description"": ""Success"",
            ""content"": {
              ""application/json"": {
                ""schema"": {
                  ""type"": ""array"",
                  ""items"": {
                    ""type"": ""string""
                  }
                }
              }
            }
          }
        }
      },
      ""post"": {
        ""operationId"": ""createItem"",
        ""summary"": ""Create item"",
        ""parameters"": [
          {
            ""name"": ""X-Custom-Header"",
            ""in"": ""header"",
            ""required"": true,
            ""schema"": {
              ""type"": ""string""
            }
          }
        ],
        ""responses"": {
          ""201"": {
            ""description"": ""Created""
          }
        }
      }
    }
  }
}
";

    [Test]
    public async Task Can_Generate_Code()
    {
        string generatedCode = await GenerateCode();
        generatedCode.Should().NotBeNullOrWhiteSpace();
    }

    [Test]
    public async Task Can_Build_Generated_Code()
    {
        string generatedCode = await GenerateCode();
        BuildHelper
            .BuildCSharp(generatedCode)
            .Should()
            .BeTrue();
    }

    [Test]
    public async Task Generated_Code_Does_Not_Contain_Auto_Generated_Header()
    {
        string generatedCode = await GenerateCode();
        generatedCode.Should().NotContain("This code was generated by Refitter");
    }

    [Test]
    public async Task Generated_Code_Does_Not_Contain_Accept_Headers()
    {
        string generatedCode = await GenerateCode();
        generatedCode.Should().NotContain("Headers(\"Accept:");
    }

    [Test]
    public async Task Generated_Code_Does_Not_Contain_Operation_Headers()
    {
        string generatedCode = await GenerateCode();
        generatedCode.Should().NotContain("[Header(\"X-Custom-Header\")]");
    }

    private static async Task<string> GenerateCode()
    {
        var swaggerFile = await SwaggerFileHelper.CreateSwaggerFile(OpenApiSpec);
        try
        {
            var settings = new RefitGeneratorSettings
            {
                OpenApiPath = swaggerFile,
                AddAutoGeneratedHeader = false,
                AddAcceptHeaders = false,
                GenerateOperationHeaders = false
            };
            var generator = await RefitGenerator.CreateAsync(settings);
            return generator.Generate();
        }
        finally
        {
            if (File.Exists(swaggerFile))
            {
                File.Delete(swaggerFile);
            }

            var directory = Path.GetDirectoryName(swaggerFile);
            if (directory != null && Directory.Exists(directory))
            {
                Directory.Delete(directory, true);
            }
        }
    }
}
