using FluentAssertions;
using Refitter.Core;
using Refitter.Tests.Build;
using Refitter.Tests.TestUtilities;

namespace Refitter.Tests.Parameters;

[Category("Integration")]
public class RouteParameterOrderingTests
{
    /// <summary>
    /// OpenAPI spec where path parameters are defined in reverse order
    /// relative to their appearance in the URL template.
    ///
    /// URL:  /items/{paramA}/{paramB}/details
    /// Spec: paramB first, then paramA
    ///
    /// The expected URL appearance order is: paramA, paramB
    /// The spec definition order is:          paramB, paramA
    ///
    /// Refitter's <see cref="RouteParameterExtractor"/> extracts parameters
    /// from <c>CSharpOperationModel.Parameters</c> in the order NSwag provides
    /// them — i.e., the OpenAPI document parameter definition order — without
    /// any sorting by URL position. This is the bug this test proves.
    /// </summary>
    private const string OpenApiSpecWithReversedPathParameters = @"
{
  ""openapi"": ""3.0.1"",
  ""info"": {
    ""title"": ""Test"",
    ""version"": ""1.0""
  },
  ""paths"": {
    ""/items/{paramA}/{paramB}/details"": {
      ""get"": {
        ""parameters"": [
          {
            ""name"": ""paramB"",
            ""in"": ""path"",
            ""required"": true,
            ""schema"": {
              ""type"": ""string""
            }
          },
          {
            ""name"": ""paramA"",
            ""in"": ""path"",
            ""required"": true,
            ""schema"": {
              ""type"": ""string""
            }
          }
        ],
        ""responses"": {
          ""200"": {
            ""description"": ""Success""
          }
        }
      }
    }
  }
}
";

    /// <summary>
    /// Swagger 2.0 equivalent of <see cref="OpenApiSpecWithReversedPathParameters"/>.
    /// Same path /items/{paramA}/{paramB}/details with reversed parameter definition order.
    /// Uses "swagger": "2.0" and direct "type": "string" on parameters instead of "schema".
    /// </summary>
    private const string OpenApiV2SpecWithReversedPathParameters = @"
{
  ""swagger"": ""2.0"",
  ""info"": {
    ""title"": ""Test"",
    ""version"": ""1.0""
  },
  ""paths"": {
    ""/items/{paramA}/{paramB}/details"": {
      ""get"": {
        ""parameters"": [
          {
            ""name"": ""paramB"",
            ""in"": ""path"",
            ""required"": true,
            ""type"": ""string""
          },
          {
            ""name"": ""paramA"",
            ""in"": ""path"",
            ""required"": true,
            ""type"": ""string""
          }
        ],
        ""responses"": {
          ""200"": {
            ""description"": ""Success""
          }
        }
      }
    }
  }
}
";

    [Test]
    [Arguments(OpenApiSpecWithReversedPathParameters)]
    [Arguments(OpenApiV2SpecWithReversedPathParameters)]
    public async Task Parameters_Are_In_Url_Order_Not_Spec_Definition_Order(string openApiSpec)
    {
        string generatedCode = await GenerateCode(openApiSpec);

        // RouteParameterExtractor now sorts parameters by their position
        // in the URL template. The fix ensures URL appearance order,
        // regardless of OpenAPI spec definition order.
        //
        // URL:         /items/{paramA}/{paramB}/details
        // Spec order:  paramB, paramA  (paramB defined first)
        // URL order:   paramA, paramB
        //
        // The correct behavior is URL order (paramA, paramB),
        // which is what the fix now produces.

        // Verify the [Get(...)] attribute exists with the correct URL template
        var lines = generatedCode.Split('\n')
            .Select(line => line.TrimEnd('\r'))
            .ToArray();

        var getIndex = Array.FindIndex(
            lines,
            line => line.Contains("[Get(\"/items/{paramA}/{paramB}/details\")]"));

        getIndex.Should().BeGreaterThanOrEqualTo(
            0,
            because:
            "the generated code should contain a [Get] attribute with the correct URL template");

        // The method signature is on the next line after the [Get] attribute.
        // Verify parameters appear in URL order (paramA before paramB).
        var methodLine = lines[getIndex + 1];
        methodLine.Should().Contain("string paramA, string paramB");
        methodLine.Should().NotContain("string paramB, string paramA");
    }

    /// <summary>
    /// Verifies that the code generated by Refitter compiles successfully against
    /// Refit. This is an end-to-end validation that proves:
    ///
    /// 1. Refitter produces a valid Refit interface with correct syntax.
    /// 2. The parameters are ordered by URL position (paramA before paramB).
    /// 3. Refit's source generator can consume the interface and produce a valid
    ///    implementation.
    ///
    /// Because Refit's source generator processes method parameters in declaration
    /// order, the <c>BuildRequestPath</c> tuples will appear in the same order as
    /// the parameters in the generated method signature. Since the existing test
    /// <see cref="Parameters_Are_In_Url_Order_Not_Spec_Definition_Order"/> confirms
    /// parameters are in URL offset order, a successful compilation proves the
    /// <c>BuildRequestPath</c> tuples are correctly ordered by URL offset.
    ///
    /// URL:         /items/{paramA}/{paramB}/details
    /// Offsets:     paramA -> (7, 15), paramB -> (16, 24)
    /// Spec order:  paramB (first), paramA (second)
    /// URL order:   paramA (first), paramB (second)
    /// </summary>
    [Test]
    [Arguments(OpenApiSpecWithReversedPathParameters)]
    [Arguments(OpenApiV2SpecWithReversedPathParameters)]
    public async Task Generated_Code_Compiles_Successfully_Against_Refit(string openApiSpec)
    {
        string generatedCode = await GenerateCode(openApiSpec);

        // Verify the generated code compiles against Refit.
        // A successful build means Refit's source generator can process the
        // interface and produce a valid stub. Since parameters are in URL
        // order in the interface (verified by Parameters_Are_In_Url_Order...),
        // Refit's BuildRequestPath will receive tuples in ascending offset order.
        BuildHelper
            .BuildCSharp(generatedCode)
            .Should()
            .BeTrue(
                because:
                "the generated Refit interface must compile against Refit, proving " +
                "that the parameter ordering is valid for the source generator");
    }

    private static async Task<string> GenerateCode(string openApiSpec)
    {
        var swaggerFile = await SwaggerFileHelper.CreateSwaggerJsonFile(openApiSpec);

        var settings = new RefitGeneratorSettings
        {
            OpenApiPath = swaggerFile
        };

        var generator = await RefitGenerator.CreateAsync(settings);
        return generator.Generate();
    }
}
