using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Refitter.Core.Settings;

public sealed record GenerationConfig(
    [property: JsonPropertyName("generateContracts")] bool GenerateContracts = true,
    [property: JsonPropertyName("generateClients")] bool GenerateClients = true,
    [property: JsonPropertyName("generateDisposableClients")] bool GenerateDisposableClients = false,
    [property: JsonPropertyName("generateDeprecatedOperations")] bool GenerateDeprecatedOperations = true,
    [property: JsonPropertyName("generateDefaultAdditionalProperties")] bool GenerateDefaultAdditionalProperties = true,
    [property: JsonPropertyName("multipleInterfaces")] MultipleInterfaces MultipleInterfaces = default,
    [property: JsonPropertyName("operationNameTemplate")] string? OperationNameTemplate = null,
    [property: JsonPropertyName("operationNameGenerator")] OperationNameGeneratorTypes OperationNameGenerator = default,
    [property: JsonPropertyName("generateOperationHeaders")] bool GenerateOperationHeaders = true,
    [property: JsonPropertyName("generateXmlDocCodeComments")] bool GenerateXmlDocCodeComments = true,
    [property: JsonPropertyName("generateStatusCodeComments")] bool GenerateStatusCodeComments = true,
    [property: JsonPropertyName("addAutoGeneratedHeader")] bool AddAutoGeneratedHeader = true,
    [property: JsonPropertyName("addAcceptHeaders")] bool AddAcceptHeaders = true,
    [property: JsonPropertyName("addContentTypeHeaders")] bool AddContentTypeHeaders = true,
    [property: JsonPropertyName("returnIApiResponse")] bool ReturnIApiResponse = false,
    [property: JsonPropertyName("returnIObservable")] bool ReturnIObservable = false,
    [property: JsonPropertyName("responseTypeOverride")] Dictionary<string, string>? ResponseTypeOverride = null,
    [property: JsonPropertyName("customTemplateDirectory")] string? CustomTemplateDirectory = null);
