using FluentAssertions;
using FluentAssertions.Execution;
using Refitter.Core;

namespace Refitter.Tests;

public class SettingsTests
{
    [Test]
    public void Default_Values_Should_Be_Set_Correctly()
    {
        var settings = new Settings();

        using var scope = new AssertionScope();
        settings.OpenApiPath.Should().BeNull();
        settings.SettingsFilePath.Should().BeNull();
        settings.Namespace.Should().Be("GeneratedCode");
        settings.ContractsNamespace.Should().BeNull();
        settings.OutputPath.Should().Be(Settings.DefaultOutputPath);
        settings.ContractsOutputPath.Should().BeNull();
        settings.NoAutoGeneratedHeader.Should().BeFalse();
        settings.NoXmlDocCodeComments.Should().BeFalse();
        settings.NoAcceptHeaders.Should().BeFalse();
        settings.InterfaceOnly.Should().BeFalse();
        settings.ContractOnly.Should().BeFalse();
        settings.ReturnIApiResponse.Should().BeFalse();
        settings.ReturnIObservable.Should().BeFalse();
        settings.InternalTypeAccessibility.Should().BeFalse();
        settings.UseCancellationTokens.Should().BeFalse();
        settings.NoOperationHeaders.Should().BeFalse();
        settings.IgnoredOperationHeaders.Should().NotBeNull().And.BeEmpty();
        settings.NoLogging.Should().BeFalse();
        settings.AdditionalNamespaces.Should().NotBeNull().And.BeEmpty();
        settings.ExcludeNamespaces.Should().NotBeNull().And.BeEmpty();
        settings.UseIsoDateFormat.Should().BeFalse();
        settings.MultipleInterfaces.Should().Be(MultipleInterfaces.Unset);
        settings.GenerateMultipleFiles.Should().BeFalse();
        settings.MatchPaths.Should().NotBeNull().And.BeEmpty();
        settings.Tags.Should().NotBeNull().And.BeEmpty();
        settings.SkipValidation.Should().BeFalse();
        settings.NoDeprecatedOperations.Should().BeFalse();
        settings.OperationNameTemplate.Should().BeNull();
        settings.OptionalNullableParameters.Should().BeFalse();
        settings.TrimUnusedSchema.Should().BeFalse();
        settings.KeepSchemaPatterns.Should().NotBeNull().And.BeEmpty();
        settings.IncludeInheritanceHierarchy.Should().BeFalse();
        settings.NoBanner.Should().BeFalse();
        settings.SkipDefaultAdditionalProperties.Should().BeFalse();
        settings.OperationNameGenerator.Should().Be(OperationNameGeneratorTypes.Default);
        settings.ImmutableRecords.Should().BeFalse();
        settings.UseApizr.Should().BeFalse();
        settings.UseDynamicQuerystringParameters.Should().BeFalse();
        settings.UsePolymorphicSerialization.Should().BeFalse();
        settings.GenerateDisposableClients.Should().BeFalse();
        settings.CollectionFormat.Should().Be(CollectionFormat.Multi);
        settings.SimpleOutput.Should().BeFalse();
        settings.NoInlineJsonConverters.Should().BeFalse();
        settings.IntegerType.Should().Be(IntegerType.Int32);
        settings.CustomTemplateDirectory.Should().BeNull();
    }

    [Test]
    public void Should_Allow_Setting_OpenApiPath()
    {
        var settings = new Settings { OpenApiPath = "https://example.com/openapi.json" };
        settings.OpenApiPath.Should().Be("https://example.com/openapi.json");
    }

    [Test]
    public void Should_Allow_Setting_SettingsFilePath()
    {
        var settings = new Settings { SettingsFilePath = "./settings.refitter" };
        settings.SettingsFilePath.Should().Be("./settings.refitter");
    }

    [Test]
    public void Should_Allow_Setting_Namespace()
    {
        var settings = new Settings { Namespace = "MyNamespace" };
        settings.Namespace.Should().Be("MyNamespace");
    }

    [Test]
    public void Should_Allow_Setting_ContractsNamespace()
    {
        var settings = new Settings { ContractsNamespace = "MyContracts" };
        settings.ContractsNamespace.Should().Be("MyContracts");
    }

    [Test]
    public void Should_Allow_Setting_OutputPath()
    {
        var settings = new Settings { OutputPath = "./Generated.cs" };
        settings.OutputPath.Should().Be("./Generated.cs");
    }

    [Test]
    public void Should_Allow_Setting_Flags()
    {
        var settings = new Settings
        {
            NoAutoGeneratedHeader = true,
            NoXmlDocCodeComments = true,
            NoAcceptHeaders = true,
            InterfaceOnly = true,
            ReturnIApiResponse = true,
            InternalTypeAccessibility = true,
            UseCancellationTokens = true,
            NoOperationHeaders = true,
            NoLogging = true,
            UseIsoDateFormat = true,
            SkipValidation = true,
            NoDeprecatedOperations = true,
            OptionalNullableParameters = true,
            TrimUnusedSchema = true,
            NoBanner = true,
            ImmutableRecords = true,
            UseApizr = true,
            UseDynamicQuerystringParameters = true,
            UsePolymorphicSerialization = true,
            GenerateDisposableClients = true,
            SimpleOutput = true,
            NoInlineJsonConverters = true
        };

        settings.NoAutoGeneratedHeader.Should().BeTrue();
        settings.NoXmlDocCodeComments.Should().BeTrue();
        settings.NoAcceptHeaders.Should().BeTrue();
        settings.InterfaceOnly.Should().BeTrue();
        settings.ReturnIApiResponse.Should().BeTrue();
        settings.InternalTypeAccessibility.Should().BeTrue();
        settings.UseCancellationTokens.Should().BeTrue();
        settings.NoOperationHeaders.Should().BeTrue();
        settings.NoLogging.Should().BeTrue();
        settings.UseIsoDateFormat.Should().BeTrue();
        settings.SkipValidation.Should().BeTrue();
        settings.NoDeprecatedOperations.Should().BeTrue();
        settings.OptionalNullableParameters.Should().BeTrue();
        settings.TrimUnusedSchema.Should().BeTrue();
        settings.NoBanner.Should().BeTrue();
        settings.ImmutableRecords.Should().BeTrue();
        settings.UseApizr.Should().BeTrue();
        settings.UseDynamicQuerystringParameters.Should().BeTrue();
        settings.UsePolymorphicSerialization.Should().BeTrue();
        settings.GenerateDisposableClients.Should().BeTrue();
        settings.SimpleOutput.Should().BeTrue();
        settings.NoInlineJsonConverters.Should().BeTrue();
    }

    [Test]
    public void Should_Allow_Setting_MultipleInterfaces()
    {
        var settings = new Settings { MultipleInterfaces = MultipleInterfaces.ByEndpoint };
        settings.MultipleInterfaces.Should().Be(MultipleInterfaces.ByEndpoint);

        settings.MultipleInterfaces = MultipleInterfaces.ByTag;
        settings.MultipleInterfaces.Should().Be(MultipleInterfaces.ByTag);
    }

    [Test]
    public void Should_Allow_Setting_OperationNameGenerator()
    {
        var settings = new Settings
        {
            OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromOperationId
        };
        settings.OperationNameGenerator.Should().Be(OperationNameGeneratorTypes.MultipleClientsFromOperationId);
    }

    [Test]
    public void Should_Allow_Setting_CollectionFormat()
    {
        var settings = new Settings { CollectionFormat = CollectionFormat.Csv };
        settings.CollectionFormat.Should().Be(CollectionFormat.Csv);

        settings.CollectionFormat = CollectionFormat.Ssv;
        settings.CollectionFormat.Should().Be(CollectionFormat.Ssv);

        settings.CollectionFormat = CollectionFormat.Tsv;
        settings.CollectionFormat.Should().Be(CollectionFormat.Tsv);

        settings.CollectionFormat = CollectionFormat.Pipes;
        settings.CollectionFormat.Should().Be(CollectionFormat.Pipes);
    }

    [Test]
    public void Should_Allow_Setting_IntegerType()
    {
        var settings = new Settings { IntegerType = IntegerType.Int64 };
        settings.IntegerType.Should().Be(IntegerType.Int64);

        settings.IntegerType = IntegerType.Int32;
        settings.IntegerType.Should().Be(IntegerType.Int32);
    }

    [Test]
    public void Should_Allow_Setting_String_Arrays()
    {
        var settings = new Settings
        {
            AdditionalNamespaces = new[] { "Namespace1", "Namespace2" },
            ExcludeNamespaces = new[] { "Exclude1" },
            IgnoredOperationHeaders = new[] { "Header1", "Header2" },
            MatchPaths = new[] { "^/api/.*" },
            Tags = new[] { "Tag1", "Tag2" },
            KeepSchemaPatterns = new[] { "^Model$" }
        };

        settings.AdditionalNamespaces.Should().HaveCount(2);
        settings.ExcludeNamespaces.Should().HaveCount(1);
        settings.IgnoredOperationHeaders.Should().HaveCount(2);
        settings.MatchPaths.Should().HaveCount(1);
        settings.Tags.Should().HaveCount(2);
        settings.KeepSchemaPatterns.Should().HaveCount(1);
    }

    [Test]
    public void Should_Allow_Setting_OperationNameTemplate()
    {
        var settings = new Settings { OperationNameTemplate = "{operationName}Async" };
        settings.OperationNameTemplate.Should().Be("{operationName}Async");
    }

    [Test]
    public void Should_Allow_Setting_CustomTemplateDirectory()
    {
        var settings = new Settings { CustomTemplateDirectory = "./templates" };
        settings.CustomTemplateDirectory.Should().Be("./templates");
    }

    [Test]
    public void DefaultOutputPath_Constant_Should_Be_Defined()
    {
        Settings.DefaultOutputPath.Should().Be("Output.cs");
    }
}
