using FluentAssertions;
using Refitter.Core;
using Spectre.Console.Cli;
using TUnit.Core;

namespace Refitter.Tests;

public class SettingsMapperTests
{
    [Test]
    public void Map_Should_Copy_Same_Name_Same_Type_Properties()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            PropertyNamingPolicy = PropertyNamingPolicy.PreserveOriginal,
            ReturnIApiResponse = true,
            ReturnIObservable = true,
            UseCancellationTokens = true,
            UseIsoDateFormat = true,
            MultipleInterfaces = MultipleInterfaces.ByEndpoint,
            OperationNameTemplate = "{operationName}Async",
            TrimUnusedSchema = true,
            IncludeInheritanceHierarchy = true,
            OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromOperationId,
            ImmutableRecords = true,
            UseDynamicQuerystringParameters = true,
            UsePolymorphicSerialization = true,
            GenerateDisposableClients = true,
            CollectionFormat = CollectionFormat.Csv,
            CustomTemplateDirectory = "./templates",
            SecurityScheme = "bearer",
            GenerateJsonSerializerContext = true,
            ContractsNamespace = "MyApi.Contracts",
        };

        var result = SettingsMapper.Map(settings);

        result.OpenApiPath.Should().Be("https://example.com/openapi.json");
        result.PropertyNamingPolicy.Should().Be(PropertyNamingPolicy.PreserveOriginal);
        result.ReturnIApiResponse.Should().BeTrue();
        result.ReturnIObservable.Should().BeTrue();
        result.UseCancellationTokens.Should().BeTrue();
        result.UseIsoDateFormat.Should().BeTrue();
        result.MultipleInterfaces.Should().Be(MultipleInterfaces.ByEndpoint);
        result.OperationNameTemplate.Should().Be("{operationName}Async");
        result.TrimUnusedSchema.Should().BeTrue();
        result.IncludeInheritanceHierarchy.Should().BeTrue();
        result.OperationNameGenerator.Should().Be(OperationNameGeneratorTypes.MultipleClientsFromOperationId);
        result.ImmutableRecords.Should().BeTrue();
        result.UseDynamicQuerystringParameters.Should().BeTrue();
        result.UsePolymorphicSerialization.Should().BeTrue();
        result.GenerateDisposableClients.Should().BeTrue();
        result.CollectionFormat.Should().Be(CollectionFormat.Csv);
        result.CustomTemplateDirectory.Should().Be("./templates");
        result.SecurityScheme.Should().Be("bearer");
        result.GenerateJsonSerializerContext.Should().BeTrue();
        result.ContractsNamespace.Should().Be("MyApi.Contracts");
    }

    [Test]
    public void Map_Should_Set_Default_Namespace_When_Settings_Namespace_Is_Null()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            Namespace = null,
        };

        var result = SettingsMapper.Map(settings);

        result.Namespace.Should().Be("GeneratedCode");
    }

    [Test]
    public void Map_Should_Negate_NoAutoGeneratedHeader()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoAutoGeneratedHeader = true,
        };

        var result = SettingsMapper.Map(settings);

        result.AddAutoGeneratedHeader.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_NoAcceptHeaders()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoAcceptHeaders = true,
        };

        var result = SettingsMapper.Map(settings);

        result.AddAcceptHeaders.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_InterfaceOnly_To_GenerateContracts()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            InterfaceOnly = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateContracts.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_ContractOnly_To_GenerateClients()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            ContractOnly = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateClients.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_NoOperationHeaders()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoOperationHeaders = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateOperationHeaders.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_NoXmlDocCodeComments()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoXmlDocCodeComments = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateXmlDocCodeComments.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_NoDeprecatedOperations()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoDeprecatedOperations = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateDeprecatedOperations.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Negate_SkipDefaultAdditionalProperties()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            SkipDefaultAdditionalProperties = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateDefaultAdditionalProperties.Should().BeFalse();
    }

    [Test]
    public void Map_Should_Map_InternalTypeAccessibility()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            InternalTypeAccessibility = true,
        };

        var result = SettingsMapper.Map(settings);

        result.TypeAccessibility.Should().Be(Core.TypeAccessibility.Internal);
    }

    [Test]
    public void Map_Should_Default_TypeAccessibility_To_Public()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            InternalTypeAccessibility = false,
        };

        var result = SettingsMapper.Map(settings);

        result.TypeAccessibility.Should().Be(Core.TypeAccessibility.Public);
    }

    [Test]
    public void Map_Should_Map_MatchPaths_To_IncludePathMatches()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            MatchPaths = ["/api/v1/.*", "/api/v2/.*"],
        };

        var result = SettingsMapper.Map(settings);

        result.IncludePathMatches.Should().BeEquivalentTo("/api/v1/.*", "/api/v2/.*");
    }

    [Test]
    public void Map_Should_Map_Tags_To_IncludeTags()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            Tags = ["pets", "users"],
        };

        var result = SettingsMapper.Map(settings);

        result.IncludeTags.Should().BeEquivalentTo("pets", "users");
    }

    [Test]
    public void Map_Should_Map_OptionalNullableParameters_To_OptionalParameters()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            OptionalNullableParameters = true,
        };

        var result = SettingsMapper.Map(settings);

        result.OptionalParameters.Should().BeTrue();
    }

    [Test]
    public void Map_Should_Map_ContractsOutputPath_To_ContractsOutputFolder()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            ContractsOutputPath = "./Contracts",
        };

        var result = SettingsMapper.Map(settings);

        result.ContractsOutputFolder.Should().Be("./Contracts");
    }

    [Test]
    public void Map_Should_Fallback_ContractsOutputFolder_To_OutputPath()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            OutputPath = "./CustomOutput.cs",
        };

        var result = SettingsMapper.Map(settings);

        result.ContractsOutputFolder.Should().Be("./CustomOutput.cs");
    }

    [Test]
    public void Map_Should_Set_GenerateMultipleFiles_When_ContractsOutputPath_Is_Set()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            ContractsOutputPath = "./Contracts",
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateMultipleFiles.Should().BeTrue();
    }

    [Test]
    public void Map_Should_Create_ApizrSettings_When_UseApizr_Is_True()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            UseApizr = true,
        };

        var result = SettingsMapper.Map(settings);

        result.ApizrSettings.Should().NotBeNull();
    }

    [Test]
    public void Map_Should_Set_ApizrSettings_To_Null_When_UseApizr_Is_False()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            UseApizr = false,
        };

        var result = SettingsMapper.Map(settings);

        result.ApizrSettings.Should().BeNull();
    }

    [Test]
    public void Map_Should_Create_CodeGeneratorSettings()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            NoInlineJsonConverters = true,
            IntegerType = IntegerType.Int64,
            JsonLibraryVersion = 9.0m,
        };

        var result = SettingsMapper.Map(settings);

        result.CodeGeneratorSettings.Should().NotBeNull();
        result.CodeGeneratorSettings!.InlineJsonConverters.Should().BeFalse();
        result.CodeGeneratorSettings.IntegerType.Should().Be(IntegerType.Int64);
        result.CodeGeneratorSettings.JsonLibraryVersion.Should().Be(9.0m);
    }

    [Test]
    public void Map_Should_Use_Default_JsonLibraryVersion_When_Not_Set()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            JsonLibraryVersion = null,
        };

        var result = SettingsMapper.Map(settings);

        result.CodeGeneratorSettings.Should().NotBeNull();
        result.CodeGeneratorSettings!.JsonLibraryVersion.Should().Be(8.0m);
    }

    [Test]
    public void Map_Should_Map_AuthenticationHeaderStyle_From_TryGetAuthenticationHeaderStyle()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            GenerateAuthenticationHeader = new FlagValue<string> { IsSet = true, Value = "Method" },
        };

        var result = SettingsMapper.Map(settings);

        result.AuthenticationHeaderStyle.Should().Be(AuthenticationHeaderStyle.Method);
    }

    [Test]
    public void Map_Should_Copy_Array_Properties()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            ExcludeNamespaces = ["ns1", "ns2"],
            IgnoredOperationHeaders = ["X-Custom"],
            KeepSchemaPatterns = [".*Dto"],
        };

        var result = SettingsMapper.Map(settings);

        result.ExcludeNamespaces.Should().BeEquivalentTo("ns1", "ns2");
        result.IgnoredOperationHeaders.Should().BeEquivalentTo("X-Custom");
        result.KeepSchemaPatterns.Should().BeEquivalentTo(".*Dto");
    }

    [Test]
    public void Map_Should_Copy_AdditionalNamespaces()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            AdditionalNamespaces = ["System.Text.Json"],
        };

        var result = SettingsMapper.Map(settings);

        result.AdditionalNamespaces.Should().BeEquivalentTo("System.Text.Json");
    }

    [Test]
    public void Map_Should_Handle_Null_MatchPaths()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            MatchPaths = null,
        };

        var result = SettingsMapper.Map(settings);

        result.IncludePathMatches.Should().BeEmpty();
    }

    [Test]
    public void Map_Should_Handle_Null_Tags()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            Tags = null,
        };

        var result = SettingsMapper.Map(settings);

        result.IncludeTags.Should().BeEmpty();
    }

    [Test]
    public void Map_Should_Set_GenerateMultipleFiles_From_Flag_Only()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
            GenerateMultipleFiles = true,
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateMultipleFiles.Should().BeTrue();
    }

    [Test]
    public void Map_Should_Default_Negation_Properties_To_True()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
        };

        var result = SettingsMapper.Map(settings);

        result.AddAutoGeneratedHeader.Should().BeTrue();
        result.AddAcceptHeaders.Should().BeTrue();
        result.GenerateContracts.Should().BeTrue();
        result.GenerateClients.Should().BeTrue();
        result.GenerateOperationHeaders.Should().BeTrue();
        result.GenerateXmlDocCodeComments.Should().BeTrue();
        result.GenerateDeprecatedOperations.Should().BeTrue();
        result.GenerateDefaultAdditionalProperties.Should().BeTrue();
    }

    [Test]
    public void Map_Should_Default_GenerateMultipleFiles_To_False()
    {
        var settings = new Settings
        {
            OpenApiPath = "https://example.com/openapi.json",
        };

        var result = SettingsMapper.Map(settings);

        result.GenerateMultipleFiles.Should().BeFalse();
    }

}
