using System.Diagnostics.CodeAnalysis;

namespace Refitter.Core;

[ExcludeFromCodeCoverage]
public class RefitGeneratorSettings
{
    public string OpenApiPath { get; set; } = null!;

    public string Namespace { get; set; } = "GeneratedCode";

    public NamingSettings Naming { get; set; } = new();

    public bool GenerateContracts { get; set; } = true;

    public bool GenerateXmlDocCodeComments { get; set; } = true;

    public bool AddAutoGeneratedHeader { get; set; } = true;

    public bool ReturnIApiResponse { get; set; }

    public bool GenerateOperationHeaders { get; set; } = true;

    public TypeAccessibility TypeAccessibility { get; set; } = TypeAccessibility.Public;

    public bool UseCancellationTokens { get; set; }

    public bool UseIsoDateFormat { get; set; }
}

[ExcludeFromCodeCoverage]
public class NamingSettings
{
    public bool UseOpenApiTitle { get; set; } = true;

    public string InterfaceName { get; set; } = "ApiClient";
}

public enum TypeAccessibility
{
    Public,
    Internal
}