using Refitter.Core;

namespace Refitter.Tests.Parity;

/// <summary>
/// Settings variants that the golden-output parity harness generates for every spec.
/// Mirrors the variants in test/smoke-tests.ps1 and adds <see cref="CodeGeneratorSettings"/> coverage.
/// </summary>
public static class ParityVariants
{
    public static IReadOnlyList<string> LargeSpecVariants { get; } = ["Default", "NullCodeGeneratorSettings"];

    public static IReadOnlyDictionary<string, Action<RefitGeneratorSettings>> All { get; } =
        new Dictionary<string, Action<RefitGeneratorSettings>>
        {
            // The CLI always creates CodeGeneratorSettings; the library, MSBuild and source generator may not
            ["Default"] = _ => { },
            ["NullCodeGeneratorSettings"] = s => s.CodeGeneratorSettings = null,

            // Refit interface options (test/smoke-tests.ps1)
            ["Cancellation"] = s => s.UseCancellationTokens = true,
            ["Internal"] = s => s.TypeAccessibility = TypeAccessibility.Internal,
            ["UsingApiResponse"] = s => s.ReturnIApiResponse = true,
            ["UsingIObservable"] = s => s.ReturnIObservable = true,
            ["UsingIsoDateFormat"] = s => s.UseIsoDateFormat = true,
            ["MultipleInterfacesByEndpoint"] = s => s.MultipleInterfaces = MultipleInterfaces.ByEndpoint,
            ["MultipleInterfacesByTag"] = s => s.MultipleInterfaces = MultipleInterfaces.ByTag,
            ["ContractOnly"] = s => s.GenerateClients = false,
            ["InterfaceOnly"] = s => s.GenerateContracts = false,
            ["DynamicQuerystring"] = s => s.UseDynamicQuerystringParameters = true,
            ["TrimUnusedSchema"] = s => s.TrimUnusedSchema = true,
            ["OptionalNullable"] = s => s.OptionalParameters = true,
            ["NoDeprecated"] = s => s.GenerateDeprecatedOperations = false,
            ["NoAutoGeneratedHeader"] = s => s.AddAutoGeneratedHeader = false,
            ["NoAcceptHeaders"] = s => s.AddAcceptHeaders = false,
            ["SkipDefaultAdditionalProps"] = s => s.GenerateDefaultAdditionalProperties = false,
            ["NoXmlDocComments"] = s => s.GenerateXmlDocCodeComments = false,
            ["NoOperationHeaders"] = s => s.GenerateOperationHeaders = false,
            ["PreserveOriginal"] = s => s.PropertyNamingPolicy = PropertyNamingPolicy.PreserveOriginal,
            ["Disposable"] = s => s.GenerateDisposableClients = true,
            ["ImmutableRecords"] = s => s.ImmutableRecords = true,
            ["PolymorphicSerialization"] = s => s.UsePolymorphicSerialization = true,
            ["CollectionFormatCsv"] = s => s.CollectionFormat = CollectionFormat.Csv,
            ["JsonSerializerContext"] = s => s.GenerateJsonSerializerContext = true,
            ["MultipleFiles"] = s => s.GenerateMultipleFiles = true,
            ["ContractTypeSuffix"] = s => s.ContractTypeSuffix = "Dto",
            ["OperationNameFromOperationId"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.SingleClientFromOperationId,
            ["OperationNameFromPathSegments"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.SingleClientFromPathSegments,
            ["OperationNameMultipleFromOperationId"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromOperationId,
            ["OperationNameMultipleFromPathSegments"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromPathSegments,
            ["OperationNameFirstTagAndOperationId"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromFirstTagAndOperationId,
            ["OperationNameFirstTagAndOperationName"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromFirstTagAndOperationName,
            ["OperationNameFirstTagAndPathSegments"] =
                s => s.OperationNameGenerator = OperationNameGeneratorTypes.MultipleClientsFromFirstTagAndPathSegments,
            ["OperationNameTemplate"] = s => s.OperationNameTemplate = "{operationName}Async",
            ["TagFiltered"] = s => s.IncludeTags = ["pet", "user", "store"],
            ["MatchPathFiltered"] = s => s.IncludePathMatches = ["^/pet/.*"],
            ["TrimWithInheritanceHierarchy"] = s =>
            {
                s.TrimUnusedSchema = true;
                s.IncludeInheritanceHierarchy = true;
            },
            ["AuthenticationHeaderMethod"] = s => s.AuthenticationHeaderStyle = AuthenticationHeaderStyle.Method,
            ["AuthenticationHeaderParameter"] = s => s.AuthenticationHeaderStyle = AuthenticationHeaderStyle.Parameter,
            ["AdditionalNamespace"] = s => s.AdditionalNamespaces = ["System.ComponentModel"],
            ["ExcludeNamespace"] = s => s.ExcludeNamespaces = ["System.Xml.Serialization"],
            ["ContractsNamespace"] = s =>
            {
                s.ContractsNamespace = "GeneratedCode.Contracts";
                s.GenerateMultipleFiles = true;
            },
            ["NoStatusCodeComments"] = s => s.GenerateStatusCodeComments = false,
            ["NoIAsyncEnumerable"] = s => s.ReturnIAsyncEnumerable = false,
            ["NoContentTypeHeaders"] = s => s.AddContentTypeHeaders = false,
            ["NoOpenApiTitle"] = s => s.Naming.UseOpenApiTitle = false,
            ["DependencyInjection"] = s => s.DependencyInjectionSettings = new DependencyInjectionSettings
            {
                BaseUrl = "https://example.com",
                TransientErrorHandler = TransientErrorHandler.HttpResilience,
            },
            ["Apizr"] = s =>
            {
                s.ApizrSettings = new ApizrSettings { WithRequestOptions = true, WithRegistrationHelper = true };
                s.OptionalParameters = true;
            },

            // Contract generation options (CodeGeneratorSettings)
            ["IntegerTypeInt64"] = s => s.CodeGeneratorSettings!.IntegerType = IntegerType.Int64,
            ["NoInlineJsonConverters"] = s => s.CodeGeneratorSettings!.InlineJsonConverters = false,
            ["JsonLibraryVersion9"] = s => s.CodeGeneratorSettings!.JsonLibraryVersion = 9.0m,
            ["NullableReferenceTypes"] = s =>
            {
                s.CodeGeneratorSettings!.GenerateNullableReferenceTypes = true;
                s.CodeGeneratorSettings.GenerateOptionalPropertiesAsNullable = true;
            },
            ["CustomCollectionTypes"] = s =>
            {
                s.CodeGeneratorSettings!.ArrayType = "System.Collections.Generic.List";
                s.CodeGeneratorSettings.ArrayInstanceType = "System.Collections.Generic.List";
                s.CodeGeneratorSettings.DictionaryType = "System.Collections.Generic.Dictionary";
            },
            ["ImmutableCollections"] = s =>
            {
                s.CodeGeneratorSettings!.GenerateImmutableArrayProperties = true;
                s.CodeGeneratorSettings.GenerateImmutableDictionaryProperties = true;
            },
            ["CustomDateTypes"] = s =>
            {
                s.CodeGeneratorSettings!.DateType = "System.DateTime";
                s.CodeGeneratorSettings.DateTimeType = "System.DateTime";
                s.CodeGeneratorSettings.DateFormat = "yyyy-MM-dd";
            },
            ["NoDataAnnotations"] = s => s.CodeGeneratorSettings!.GenerateDataAnnotations = false,
            ["NoDefaultValues"] = s => s.CodeGeneratorSettings!.GenerateDefaultValues = false,
            ["NativeRecords"] = s => s.CodeGeneratorSettings!.GenerateNativeRecords = true,
            ["InternalSetters"] = s => s.CodeGeneratorSettings!.PropertySetterAccessModifier = "internal",
            ["InlineNamedTypes"] = s =>
            {
                s.CodeGeneratorSettings!.InlineNamedArrays = true;
                s.CodeGeneratorSettings.InlineNamedDictionaries = true;
                s.CodeGeneratorSettings.InlineNamedAny = true;
            },
            ["AnyTypeJsonElement"] = s => s.CodeGeneratorSettings!.AnyType = "System.Text.Json.JsonElement",
            ["EnforceFlagEnums"] = s => s.CodeGeneratorSettings!.EnforceFlagEnums = true,
        };
}
