openapi: 3.0.1
info:
  title: Nothing to merge
  version: 1.0.0
paths:
  /pets:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'empty.yaml#/components/schemas/Pet'
