name: MSBuild Tasks

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/msbuild.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
  pull_request:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/msbuild.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'

jobs:
  build:
    name: 👌 Verify build
    runs-on: windows-latest
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v6
    - name: 🛠️ Prepare
      working-directory: test/MSBuild
      run: |
        dotnet restore ../../src/Refitter.slnx
        dotnet build -c release ../../src/Refitter/Refitter.csproj
        dotnet build -c release ../../src/Refitter.MSBuild/Refitter.MSBuild.csproj
        dotnet pack -c release ../../src/Refitter.MSBuild/Refitter.MSBuild.csproj -o .
        nuget add .\Refitter.MSBuild.1.0.0.nupkg -source .
        dotnet add package Refitter.MSBuild -s .
    - name: 🛠️ Build (default naming)
      working-directory: test/MSBuild
      run: dotnet build -v d -filelogger
    - name: 🧪 Build Output (default)
      working-directory: test/MSBuild
      run: cat msbuild.log
    - name: 🛠️ Build (PreserveOriginal naming)
      working-directory: test/MSBuild
      run: |
        dotnet clean -c release --nologo
        dotnet build -c release -v d -filelogger
    - name: 🧪 Build Output (PreserveOriginal)
      working-directory: test/MSBuild
      run: cat msbuild.log
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v7
      with:
        name: Packages
        path: |
          **/*.nupkg
          README.md
