name: MSBuild Tasks

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/msbuild.yml'
      - 'src/**/*.csproj'
      - 'src/**/*.cs'
      - 'src/**/*.targets'
      - 'src/Refitter.MSBuild/README.md'
      - 'docs/docfx_project/articles/msbuild.md'
      - 'test/MSBuild/**'

jobs:
  build:
    name: 👌 Verify build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]        
    runs-on: ${{ matrix.os }}
    steps:
    - name: 🛒 Checkout repository
      uses: actions/checkout@v7
    - name: 🛠️ Build
      working-directory: test/MSBuild
      shell: pwsh
      run: ./build.ps1
    - name: 🗳️ Upload
      uses: actions/upload-artifact@v7
      with:
        name: Packages-${{ matrix.os }}
        path: |
          **/*.nupkg
          README.md
