name: Release (Preview)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 2.2.0-preview.${{ github.run_number }}
    secrets: inherit
