name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/release-template.yml
    with:
      version: 2.2.0
    secrets: inherit
